bigcommerce/paper-handlebars

- index.js
- lib/logger.js
- package.json
- spec/index.js
- spec/lib/logger.js
- spec/spec-helpers.js
* Add error handling around restoring precompiled templates, rendering templates, compiling templates, looking up templates
* Update addTemplates so it can handle a mix of precompiled templates and raw template strings
* Better detection of precompiled templates before doing a potentially dangerous eval.
* Add logger and ability for caller to set a logger
`npm test`
----
> Add better error handling

- CHANGELOG.md
- helpers/getFontsCollection.js
- helpers/getImage.js
- helpers/lib/cdnify.js
- helpers/money.js
- helpers/stylesheet.js
- index.js
- package.json
- spec/helpers/region.js
- spec/index.js
* Change addContent() to setContent() for consistency with other setters.
* Add getter and setter for siteSettings and themeSettings, and change helper context
to use a bound function for accessing these data to allow for deferred setting.
Callers should no longer access siteSettings and themeSettings directly.
`npm test`
----
> STRF-4420: Add deferred access to siteSettings and themeSettings

- CHANGELOG.md
- helpers/lib/cdnify.js
- helpers/stylesheet.js
- package.json
- spec/index.js
In the `cdn` and `stylesheet` helpers, we were making the call to `getThemeSettings` and `getSiteSettings` at the wrong time, so not getting the latest value if they were updated after construction.
Unit tests added
----
> STRF-4420: Fix scope of call to getSiteSettings

- helpers/if.js
- package.json
- spec/helpers/if.js
Under the "if" helper we didn't have a case for number strings that convert string that are numbers and compare them.This pr will add "gtnum" which takes an input of string -> convert them to integers and check if left grater than right. 
specs and manually.
> added under if helpers comparison of number string

- helpers/lib/cdnify.js
- package.json
- spec/helpers/cdn.js
Currently we are generating cdn link for img/icon-sprite.svg with double slash (//img/icon-sprite.svg). This fix handle this case and avoid double slash.
Unitest and manually.
----
> Handle case in cdn helper for img/icon-sprite.svg

- helpers/region.js
- spec/helpers/region.js
Currently we are not rendering regions unless there is a widget in any region. This logic has changed between the old paper helper and the new paper-handlebars. This restores the original behavior.
----
> MERC-4360: Always render regions

- helpers/lib/fonts.js
- spec/helpers/getFontsCollection.js
This simple change allows us to use `{{ getFontsCollection }}` in the AMP layout.
Calling `{{ getFontsCollection }}` will return
`<link href="https://fonts.googleapis.com/css?family=..........">` 
rather than 
`<link href="//fonts.googleapis.com/css?family=..........">`
We spotted this issue in our first round of UAT for a new theme we are preparing.
Presently, including `{{ getFontsCollection }}` in `layout/amp.html` to keep branding consistent and bring in fonts used in the theme results in a validation error on the [Google AMP Test site](https://search.google.com/test/amp).
Currently to bring in all theme fonts to the AMP templates without a validation error requires we use the following Handlebars:
`<link href="https://fonts.googleapis.com/css?family={{first (last (split …
> Include protocol in the Google Fonts URL

- helpers/resourceHints.js
- spec/helpers/resourceHints.js
* We now always connect to Google font hosts using https so update the resource hints to match
* Get rid of ajax.googleapis.com, which are unused in Cornerstone currently
`npm test`
----
> STRF-5711: Update resource hints

- CHANGELOG.md
- helpers/lib/cdnify.js
- package.json
- spec/helpers/cdn.js
Currently, cdn helper is not handling relative path and not trim . or / from the begging of the path before creating cdn url. That cause paths such as ../example.com ,  ./example.com ,  /example.com,  ../../example.com, etc to generate wrong cdn url which leads to a wrong request by the browser (return 404)
Unitests
----
> trimmed . and / in cdn helper for paths which are not full path

- index.js
Fix regex performance to match precompiled templates.
`.*` at the beginning is forcing it to match all characters and for a big precompiled template file it takes over 10 sec.
The regex was matching every 
cc @bigcommerce/storefront-team @bigcommerce/platform-engineering
> STRF-6040 Fix regex performance to match precompiled templates.

- helpers/getFontsCollection.js
- helpers/lib/fonts.js
- spec/helpers/getFontsCollection.js
Change default behavior of {{getFontsCollection}} to use font-display: swap; for Google Fonts, allow configuration
----
Unit tested can run test suite to check.
> STRF-6687 Change default behavior of {{getFontsCollection}} to use font-display: swap; for Google Fonts, allow configuration

- CHANGELOG.md
- helpers/lib/fonts.js
STRF-6702 Remove the usage of the fontKeyFormat regex in the font helpers.  Regex is expensive and this is an alternative to that.
----
Unit tests pass.
Ran an analysis on regular expression analyzer and found that regex was equivalent to that there needs to be a word character before the occurrence of '-font' and '-font' needs to be end of string.  Word characters in ecmascript are [^a-zA-Z_0-9].  
> strf-6702 remove regex in font helpers

- CHANGELOG.md
- helpers/all.js
- helpers/any.js
- helpers/block.js
- helpers/compare.js
- helpers/contains.js
- helpers/for.js
- helpers/getFontsCollection.js
- helpers/if.js
- helpers/join.js
- helpers/lang.js
- helpers/or.js
- helpers/partial.js
- helpers/replace.js
- helpers/stylesheet.js
- helpers/unless.js
- spec/helpers/block.js
- spec/helpers/stylesheet.js
STRF 6707 Don't use arguments in helpers.  Move away from arguments pattern so that performance may be improved.
----
Added unit test for for helper fix and current unit tests don't break.
> STRF-6707 Don't use arguments in helpers

- CHANGELOG.md
- helpers/for.js
- spec/helpers/for.js
STRF-6836 For helper should iterate once.  Previously for helper would iterate twice at the minimum and now it is able to iterate once at minimum.
Fixes #28 
----
Added unit tests and tests pass.
> STRF-6836 For helper should iterate once

- CHANGELOG.md
- helpers/all.js
- helpers/deprecated/pick.js
- helpers/for.js
- helpers/getImage.js
- helpers/if.js
- helpers/lib/common.js
- helpers/limit.js
- helpers/money.js
- helpers/or.js
- helpers/stylesheet.js
STRF-6701 Renderer: Reduce usage of Lodash.  Lodash utility methods can be slow especially things like _.each and this is a pr to improve performance of Storefront Renderer by moving to native JavaScript methods and for loops.
----
Unit tests still pass.
> STRF-6701 Renderer: reduce usage of Lodash

- helpers/getImage.js
- helpers/lib/common.js
- spec/helpers/getImage.js
Making getImage return a ` SafeString` instead of a string.
This is because `&` is a special character which gets escaped by Handlebars, which breaks query strings with more than 1 argument in image URLs.
This happens in production today with `imbypass`, example:
https://cdn11.bigcommerce.com/s-grief/images/stencil/1280x1280/products/7295/4490/122901_8k-wallpaper__18797.1558901341.jpg?c=3&amp;imbypass=on
Not that query string should be `?c=3&imbypass=on` but is instead `?c=3&amp;imbypass=on`.
We already have decent checking on this to make sure it's a real image object before we parse it, so this change feels okay to me - but I'm interested to hear from @mattolson on that.
I discovered this while testing https://github.com/bigcommerce/paper-handlebars/pull/53
Unit tests on getImage still …
> Return image URL as SafeString

- helpers/getImageSrcset.js
- package.json
- spec/helpers.js
- spec/helpers/getImageSrcset.js
Adding a helper to make it easy to get a `srcset` string for an image.
The API is meant to feel familiar to a user of `getImage`.
Intended HTML usage:
`<img src="{{getImage image "default"}}" srcset="{{getImageSrcset image 100w="100w" 200w="200w" 300w="300w"}}" />`
Output would look like:
`https://cdn00.bigcommerce.com/s-abc123/images/stencil/100w/l/my-huge-image.original.jpg 100w, https://cdn00.bigcommerce.com/s-abc123/images/stencil/200w/l/my-huge-image.original.jpg 200w, https://cdn00.bigcommerce.com/s-abc123/images/stencil/300w/l/my-huge-image.original.jpg 300w`
Or perhaps:
```
`<img src="{{getImage image "default"}}" srcset="{{getImageSrcset image 1x="1000x1000" 2x="2000x2000"}}" />`
```
For this result:
`https://cdn00.bigcommerce.com/s-abc123/images/stencil/1000x1000/l/my-huge-image. …
> Add getImageSrcset helper

- CHANGELOG.md
- helpers/all.js
- helpers/any.js
- helpers/contains.js
- helpers/getFontsCollection.js
- helpers/or.js
- spec/helpers/if.js
https://jira.bigcommerce.com/browse/STRF-6967
Rest parameters are considered more performant than arguments when processing input as an array and call is unacceptable for correct arguments usage.  Other usages such as .length and indexing into valid indices of arguments object are considered ok and not a deoptimization issue.
Unit tests still pass.
----
> STRF-6967: Move away from arguments usage

- CHANGELOG.md
- helpers/all.js
- helpers/any.js
- helpers/contains.js
- helpers/lib/fonts.js
- helpers/or.js
- helpers/pluck.js
- helpers/resourceHints.js
- helpers/stylesheet.js
- package.json
Upgrade Lodash due to known security vulnerability in 3.10.1.
https://jira.bigcommerce.com/browse/STRF-6968
An example of an article that mentions minimal performance difference is https://btux1984.wordpress.com/2018/10/06/why-you-should-still-embrace-lodash/
Based on this to gain a performance increase then we can only really do microoptimizations by refactoring everything to a for loop.
A response to https://codeburst.io/why-you-shouldnt-use-lodash-anymore-and-use-pure-javascript-instead-c397df51a66
https://medium.com/@cloud_guy/imo-lodash-is-not-bad-at-all-c8530d9da879
JS fiddle of that response: 
https://jsfiddle.net/o7g30d9r/
----
The unit tests pass with the replacements of the deprecated functions.
> STRF-6968 upgrade lodash

- helpers/all.js
- helpers/any.js
- helpers/for.js
- helpers/getImage.js
- helpers/if.js
- helpers/limit.js
- helpers/or.js
Swapping out lodash methods with handlebars-utils, which is a little nicer for handlebars.
Unit tests still pass.
----
> Refactor lodash methods to use handlebars-utils instead

- CHANGELOG.md
- package.json
Release 4.0.10
- Upgrade Lodash to 4.17.13
- Reduce arguments usage where possible
- Refactor helper functions to use Handlebars utils type checks instead of Lodash type checks
- Add getImageSrcset helper
- Refactor getImage helper to return image URL as SafeString instead of string
> STRF-7011 Release 4.0.10

- CHANGELOG.md
- helpers/getImage.js
- package.json
- spec/helpers/getImage.js
Surgical revert of https://github.com/bigcommerce/paper-handlebars/pull/61
SafeString on getImage caused some issues on production themes, with markup like this:
`{{#if (stripQuerystring (getImage ../product.main_image 'product_size' (cdn ../theme_settings.default_image_product))) '==' (stripQuerystring (getImage this 'product_size' (cdn ../theme_settings.default_image_product))) }}is-active is-main{{/if}}`
Un-doing it for now. Folks can use triple-braces in the meantime.
Unit tests, and confirmed in local dev that a previously broken theme is now fixed.
----
> Undo safestring change to getImage and release 4.1.1

- CHANGELOG.md
- helpers/getImage.js
- package.json
- spec/helpers/getImage.js
Putting the changes from https://github.com/bigcommerce/paper-handlebars/pull/61 back now that the bug with `stripQuerystring` has been fixed in https://github.com/bigcommerce/paper-handlebars/pull/67. Releasing 4.1.2.
Unit tests.
> Put getImage safestring back, release 4.1.2

- helpers/getImage.js
- helpers/getImageSrcset.js
- spec/helpers/getImage.js
- spec/helpers/getImageSrcset.js
- spec/helpers/if.js
Modify behavior of `getImageSrcset` to only generate srcsets up to the size of the image, *if* we know the image dimensions.
Assumes we'll make updates to pass the dimensions of images into the context in the future.
Today, we could do this for carousel images, which should help optimize home page load speed and reduce inefficiency in the HTML if carousel images less than our maximum sizes are uploaded.
Added unit test.
----
> Only generate srcsets up to the dimensions of the image (if known)

- helpers/setURLQueryParam.js
- spec/helpers.js
- spec/helpers/setURLQueryParam.js
Adds new `setURLQueryParam` helper to help with manipulating query strings on URLs.
Unit tests added.
> Add setURLQueryParam helper

- helpers/json.js
- spec/helpers/json.js
A partner has reported an issue using the `{{getImage}}` helper as a nested expression on the `{{json}}` helper: https://support.bigcommerce.com/s/question/0D51B00005aDurSSAS/sudden-change-in-how-stencil-json-getimage-works
This fixes that by first unwrapping `SafeString`s before processing.
This doesn't really violate the object model in my opinion, as these are handlebars rendering internal details.
Added a unit test.
----
> Fix json helper to work with a nested getImage helper

- CHANGELOG.md
- index.js
- package.json
https://jira.bigcommerce.com/browse/STRF-7393
There was an issue with the addTemplates function that caused stencil cli to lose templates when paper was on the 3.x branch this pr should fix the issue. 
Stencil cli add to cart, edit cart and delete cart along with other JavaScript functionality works as expected now with the paper 3.x branch when tested locally
----
> STRF-7393 fix addTemplates logic to not lose templates

- helpers/encodeHtmlEntities.js
- spec/helpers/encodeHtmlEntities.js
Add support for more of the arguments on `he` module for more flexibility in HTML encoding.
I added support for [all of these arguments](https://github.com/mathiasbynens/he#heencodetext-options) except `strict` because I don't think it's useful in this context.
Unit tests.
----
> Add the arguments that `he` supports on encodeHtmlEntities

- helpers/replace.js
- spec/helpers/replace.js
Unwrap `safestring` inputs to `replace` helper, so it can be used more gracefully with other helpers.
Unit tests.
----
cc @bigcommerce/storefront-team @bigcommerce/artemis-dt
> Allow replace helper to handle safestrings

- helpers/any.js
- spec/helpers/any.js
Adds test coverage for any helper in support of dropping lodash.
Unit tests added.
----
> STRF-8667: Adds test coverage for any helper

- helpers/inject.js
- spec/helpers/inject.js
Escaping values passed into jsContext through the inject helper using Handlebars escapeExpression.
Currently, users can enter values on the account page that aren't escaped, potentially opening up site visitors to XSS attacks when the values are injected into jsContext.
By escaping the values as they are injected, any unsafe values (i.e. script tags) will be rendered as plain text on the page, even if a developer is feeding them into the page with innerHTML.
Used my fork of paper-handlebars within a locally referenced version of paper with storefront-renderer running in VM. I uploaded a customized version of the latest Cornerstone to my VM store with extra account values injected on the page so I could see them in the browser inspect element console.
Injected fields:
Example of account …
> STRF-8585 Escape injected values

- helpers.js
- Refactored helpers.js to remove dependency from path and fs modules.
P.S. handlebars-helpers issue is not valid anymore. https://github.com/doowb/unlazy-loader worked for me
cc @mattolson @junedkazi
> STRF-9037 Refactored helpers.js and removed handlebars-helpers

- helpers/region.js
- spec/helpers/region.js
Region name localization support. This PR is to add `content-region-translation` data attribute if translation is provided in the html handlebars from the theme. This will be used to surface the correct translation on the front end (page builder) for a particular region.
Steps to test 
(1) Pull down the `storefront-render` [PR](https://github.com/bigcommerce/storefront-renderer/pull/280) and run locally (or can run the container image) 
(2) Pull down `stencil-cli` [PR](https://github.com/bigcommerce/stencil-cli/pull/731) and create theme with `{{{region name="header_bottom" translation="i18n.RegionName.HeaderBottom"}}}` and `i18n.RegionName.HeaderBottom` dummy translation within `schema.json`. **EXAMPLE PROVIDED BELOW**
(3) Change store language to non english language (`chinese` and …
> MERC-7830 region name localization support

- CHANGELOG.md
- package.json
Release version 4.4.8
Includes changes to support region translations data attribute. 
> Release version 4.4.8

- helpers/concat.js
- spec/helpers/cdn.js
- spec/spec-helpers.js
Concat should use global handlebars as it relies on the current theme handlebars version instead of directly importing (which is importing always version 3)
e2e and `npm test`
----
> STRF-9302 Fix concat helper to have consistency with cdn helper

- helpers/concat.js
- helpers/encodeHtmlEntities.js
- helpers/getContentImage.js
- helpers/getContentImageSrcset.js
- helpers/getImage.js
- helpers/getImageManagerImage.js
- helpers/getImageManagerImageSrcset.js
- helpers/getImageSrcset.js
- helpers/json.js
- helpers/lib/common.js
- helpers/lib/getObjectStorageImage.js
- helpers/replace.js
- helpers/setURLQueryParam.js
- helpers/stripQuerystring.js
- spec/helpers/cdn.js
Currently SafeString object is being imported from handlebars library directly in some places and from `globals.handlebars` in another. 
The first one import shouldn't be used as it imports always only v3, while `globals.handlebars` relies on the handlebars version that was used during initialization.
_npm test_
e2e on storefront
----
> STRF-9215 (fix): SafeString object is taken only from global handlebars object

- CHANGELOG.md
- package.json
Release 4.4.9
- Fix concat helper to have consistency with cdn helper ([#144](https://github.com/bigcommerce/paper-handlebars/pull/144))
- Release stencil paper handlebars through github release ([#145](https://github.com/bigcommerce/paper-handlebars/pull/145))
- SafeString object is taken only from global handlebars object ([#146](https://github.com/bigcommerce/paper-handlebars/pull/146))
----
> Release 4.4.9

- .github/workflows/release.yml
Fix Github action on Release
Replace` npm ci ` with `npm i`.
`npm ci` commonly used in automated environments: tests, deployments, etc and it's not updating package-lock.json
But the thing is, that this is a dependent library and we decided not to include package-lock.json in repo, so this command can't be used in Github Actions. 
----
> STRF-9215 (fix): Fix Github action on Release

- helpers/assignVar.js
- spec/helpers/assignVar-getVar.js
Add support for floats in assignVar/getVar helpers by customer request.
Test added.
----
> Support floats for assignVar/getVar

- CHANGELOG.md
- package.json
- Support floats for assignVar/getVar ([#152](https://github.com/bigcommerce/paper-handlebars/pull/152))
- Stop testing on node 10, start testing on node 14, release on 14 ([#151](https://github.com/bigcommerce/paper-handlebars/pull/151))
----
> Release 4.5.1

- CHANGELOG.md
- package.json
- Add log level variable to control log helper ([#158](https://github.com/bigcommerce/paper-handlebars/pull/158))
> Release 4.5.2

- CHANGELOG.md
- package.json
Snyk suggestions 
https://app.snyk.io/org/bigcommerce/project/e947f4e9-85ef-4858-a86a-82bcdd6b2452/pr-check/350f32d1-efcd-42b0-8a4a-bea671eee6be
`npm test`
----
> Bump lodash version

- helpers/money.js
- spec/helpers/money.js
Improved money helper to support input params according to the docs
`npm test`, e2e
----
> feat: STRF-9707 Improve money helper to support input params

- helpers/decrementVar.js
- helpers/dynamicComponent.js
- helpers/getVar.js
- helpers/incrementVar.js
- helpers/pluck.js
- spec/helpers/assignVar-getVar.js
- spec/helpers/decrementVar.js
- spec/helpers/dynamicComponent.js
- spec/helpers/incrementVar.js
- spec/helpers/pluck.js
More details at https://bigcommercecloud.atlassian.net/browse/STRF-9835
cdvm
> fix: STRF-9835 Reduce proto usage

- CHANGELOG.md
- package.json
- fix: STRF-9835 Reduce proto usage ([#167](https://github.com/bigcommerce/paper-handlebars/pull/167))
> chore: release 4.6.0

- CHANGELOG.md
- helpers/get.js
- helpers/getObject.js
- helpers/lib/common.js
- helpers/option.js
- spec/helpers/get.js
- spec/helpers/getObject.js
- spec/helpers/lib/common.js
- spec/helpers/option.js
[#171](https://github.com/bigcommerce/paper-handlebars/pull/171) inadvertently broke an edge case where the `concat` helper is used to dynamically generate property paths.
With the original `get` and `option` helpers, this only worked with top-level properties (not nested properties) due to an implicit `toString` conversion [here](https://github.com/jonschlinkert/get-value/blob/2.0.6/index.js#L22). This PR modifies those helpers to accept both top-level and nested property paths generated by `concat`.
_Edit: During testing & review, I noticed that the old `get` helper would retrieve empty string keys (`get({'': 0}, '')` would return `0`) and have made changes to match that behavior._
Unit tests have been added to cover cases where `concat` is used to generate property paths for helpers …
> fix: STRF 9873 make `get` etc. compatible with `concat` return value

- helpers/moment.js
- spec/helpers/moment.js
Restore some previous behavior of the `moment` helper.
Unit tests have been added for the known affected use cases.
----
> patch for helper-date 0.2.3 compatibility

- CHANGELOG.md
- package.json
- patch for helper-date 0.2.3 compatibility ([#180](https://github.com/bigcommerce/paper-handlebars/pull/180))
> Release 5.0.4

- CHANGELOG.md
- package.json
- setup to replace `get` & `getObject` helpers ([#183](https://github.com/bigcommerce/paper-handlebars/pull/183))
----
> chore: release 5.0.5

- CHANGELOG.md
- helpers/lib/common.js
- spec/helpers/get.js
- spec/helpers/lib/common.js
The new `getValue` function in `helpers/lib/common.js` was missing a check needed to safely handle cases like
```js
getValue(globals, {a: undefined}, 'a.b');
```
Unit test cases added for both `getValue` and one of the helpers using it.
----
> fix: add check for undefined/null before calling Object.keys

- CHANGELOG.md
- package.json
- bugfix for edge case affecting `get`, `getObject`, and `option` ([#185](https://github.com/bigcommerce/paper-handlebars/pull/185))
----
> chore: release 5.0.6

- helpers/cdn.js
- spec/helpers/cdn.js
enable `cdn` helper to optionally produce resource hints.
unit tests
----
> [STRF-9949] paper-handlebars - cdn helper, add new resourceHints attribute

- helpers/earlyHint.js
- spec/helpers/earlyHint.js
Removes `type` attribute in `earlyHint` helper.
It will be properly implemented in conjunction with the `as` attribute.
unit tests
----
> removes type attribute from earlyHint helper. it will be reimplemented properly.

- index.js
We're seeing a lot of errors about 'hash' undefined in renderer that spike occasionally and result in 500s https://kibana.bigcommerce.net/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2d,to:now))&_a=(columns:!(template_path,template_engine,message,store_id),filters:!(),index:production_containers_storefront-renderer,interval:auto,query:(language:kuery,query:'%22Cannot%20read%20property%20!'hash!'%20of%20null%22'),sort:!(!('@timestamp',desc)))
We're attempting to diagnose what exactly is failing within handlebars when we have a RenderError, so add the original stack trace to the error message 
----
> Add original stack trace to render error

- helpers/cdn.js
- helpers/earlyHint.js
- helpers/lib/fonts.js
- helpers/lib/resourceHints.js
- helpers/resourceHints.js
- helpers/stylesheet.js
- spec/helpers/getFontsCollection.js
- spec/helpers/lib/resourceHints.js
- spec/helpers/resourceHints.js
After fully enabling early hints an issue with URL encoding was found: the URL for google fonts in Link headers are encoded but the same URLs in the `link` tag are not encoded, leading to requesting the fonts 2 times. Check the requests in this test https://www.webpagetest.org/result/220912_BiDcW5_D8J/1/details/#waterfall_view_step1
The proposed fix in this PR is that the code responsible for creating the data for early hints will use NodeJs `url` to `parse` the paths and the `format`ed version of the valid URL will be returned so any helper using this code will then use the valid URL to generate the HTML it needs to. The `url.parse` method throws when it receives invalid data so it already helps us to produce valid URLs. It is important to note that NodeJs `url` module does not follow …
> [STRF-10096] - storefront - investigate google fonts css uri encoding issue

- helpers/3p/utils/lib/indexOf.js
- spec/helpers/3p/utils/lib/indexOf.js
Original error:
Cannot read property 'length' of undefined
Happened in inArray helper, when array is undefined.
npm test
----
> fix: STRF-10122 Fix inArray helper, when array is undefined

- CHANGELOG.md
- package.json
- fix: STRF-10122 Fix forEach, withFirst helpers makeIterator utils([#203])[https://github.com/bigcommerce/paper-handlebars/pull/203]
----
> chore: release 5.1.4

- helpers/cdn.js
- helpers/earlyHint.js
- helpers/getFontsCollection.js
- helpers/lib/fonts.js
- helpers/lib/resourceHints.js
- helpers/resourceHints.js
- helpers/stylesheet.js
- spec/helpers/cdn.js
- spec/helpers/earlyHint.js
- spec/helpers/getFontsCollection.js
- spec/helpers/resourceHints.js
- spec/helpers/stylesheet.js
- earlyHint helper now support as attribute
- cdn helper now support as attribute for early hint
- resourceHints helper, hints' cors is now anonymous to reflect the link tag that is built, also, rel now is preconnect
- renaming addResourceHint params to better reflect parity with HTLM link tag - stylesheet helper preload hint support crossorigin attr (defaulting to "no")
----
> [STRF-10120] paper-handlebars - resource hints should include the proper values for PreloadResourceType

- helpers/3p/html.js
- helpers/3p/utils/base.js
- helpers/3p/utils/index.js
- helpers/3p/utils/lib/createFrame.js
- helpers/3p/utils/lib/markdown.js
- helpers/all.js
- helpers/any.js
- helpers/assignVar.js
- helpers/decrementVar.js
- helpers/encodeHtmlEntities.js
- helpers/for.js
- helpers/getImage.js
- helpers/getImageSrcset.js
- helpers/getImageSrcset1x2x.js
- helpers/getVar.js
- helpers/if.js
- helpers/incrementVar.js
- helpers/lib/getObjectStorageImage.js
- helpers/lib/resourceHints.js
- helpers/limit.js
- helpers/moment.js
- helpers/option.js
- helpers/or.js
- helpers/resourceHints.js
- helpers/setURLQueryParam.js
- helpers/strReplace.js
- helpers/stripQuerystring.js
- helpers/stylesheet.js
- helpers/thirdParty.js
- package.json
Rework of https://github.com/bigcommerce/paper-handlebars/pull/199
npm test, cdvm
----
> STRF-10124 Clean up handlebars dependencies

- .github/workflows/build.yml
- .github/workflows/release.yml
As we don't publish package-lock.json, we can't use `npm ci` in Github Actions
----
> fix: STRF-10157 Fix build job: npm ci -> npm i

- .releaserc
- package.json
@semantic-release/exec plugin was having missing dependency
----
> fix: STRF-10157 Fix semantic release: added missing dependency

- .releaserc
Folders should use glob pattern according to [documentation](https://github.com/asbiin/semantic-release-github-pullrequest#assets) 
----
> fix: STRF-10157 Fix adding assets to Github Release

- .releaserc
Looks like we don't need dist folder in the PR, only in the github release
----
> fix: STRF-10157 Fix github release assets files

- .github/workflows/release.yml
- .releaserc
- publish.sh
Refactor how sending event data is being proceed:
1. semantic release handles knowledge of the next release and notes.
2. it sends that data to bash script via cli args
3. bash script access env vars (secrets) and cli args to send event data throught curl (github api)
----
> fix: STRF-10157 Fix sending event data to paper repo

- helpers/lib/fonts.js
- spec/helpers/getFontsCollection.js
`getFontsCollection` helper hint should be of type `style` not `font`
----
> fix: STRF-10120 getFontsCollection helper hint should be of type style not font

- helpers/block.js
- helpers/partial.js
- index.js
- spec/helpers/block.js
- spec/helpers/getObject.js
More context: https://bigcommercecloud.atlassian.net/browse/STRF-10175
`npm test`
----
> fix: STRF-10175 Allow only strings passed to partial and block helpers

- helpers/lang.js
- spec/helpers/lang.js
Fix lang helper output to have returned only strings
npm test, cdvm
----
> fix: STRF-10198 Accept only strings for lang helper output

- helpers/3p/collection.js
- helpers/3p/string.js
- spec/helpers/3p/collection.js
- spec/helpers/3p/string.js
1. `titleize` was erroring providing non-words character
2. `length` failed on null
npm test
----
> fix: STRF-10180 Improve titleize and length helpers edge cases

- helpers.js
- helpers/jsonParseSafe.js
- spec/helpers.js
- spec/helpers/jsonParseSafe.js
We have the JSONParse helper which parse JSON and return an object:
```
{{#JSONparse jsonString}}
{{name}}
{{/JSONparse}}
```
Helper works fine until non-json comes to parse. In this case it will break a page because it always expects syntactically correct JSON.
We faced with such case when parameter can be string or json and need to have a helper that can parse it safely.
According to required, we want to add a new `JSONparseSafe` helper:
```
{{#JSONparseSafe jsonString}}
{{name}}
{{/JSONparseSafe}}
{{#JSONparseSafe jsonString}}
{{name}}
{{else}}
{{string}}
{{/JSONparseSafe}}
```
So, the helper try to parse passed parameter then
- if succeeded - return an object
- if failure - do nothing
- if failure and we have else instruction - do else instruction
If you need more information please …
> feat: Add JSONparseSafe helper

- helpers/all.js
- helpers/contains.js
- helpers/deprecated/pick.js
- helpers/join.js
- helpers/pluck.js
- spec/helpers/all.js
- spec/helpers/any.js
- spec/helpers/join.js
- spec/helpers/pluck.js
- spec/helpers/thirdParty.js
Fix null params passed to handlebars helpers
npm test
----
> fix: STRF-9673 Fix null params passed to helpers

- index.js
- spec/index.js
Override default logging function with provided logger from renderer 
npm test
----
> feat: STRF-9922 Improve renderer logging

- helpers/3p/array.js
- spec/helpers/3p/first.js
- spec/helpers/3p/last.js
while testing in int i found that the following error is thrown
```
FailedPrecondition: arr.join is not a function : TypeError: arr.join is not a function
at stringAlt (/opt/app/node_modules/@bigcommerce/stencil-paper-handlebars/helpers/3p/array.js:312:16)
```
with the following template:
```html
<div style="background-color:aquamarine;">
<p style="text-align: center;">
{{first [1,2,3]}}
</p>
<p style="text-align: center;">
{{first [9,8,7,6,5,4,3,2,1] 3}}
</p>
<p style="text-align: center;">
{{first [1,2,3,4,5,6,7,8,9,0] 15}}
</p>
<p style="text-align: center;">
{{last [1,2,3]}}
</p>
<p style="text-align: center;">
{{last [9,8,7,6,5,4,3,2,1] 8}}
</p>
<p style="text-align: center;">
{{last [1,2,3,4,5,6,7,8,9,0] 15}}
</p>
</div>
<div style="background-color: aqua;">
<p style="text-align: …
```
> fix: STRF-10494 last and first helpers works with strings

- index.js
- spec/index.js
Winston doesn't have log level, so it should be converted to info level
cdvm
----
> fix: STRF-10408 Fix unknown level error

- .eslintrc
- helpers/strReplace.js
- spec/helpers/strReplace.js
strReplace helper should be able to replace with empty characters
npm test
----
> fix: Improve strReplace to remove characters

- package.json
`stringz` package version bumped to latest.
Based on the package changelog it seems safe to use the latest version as no braking changes are mentioned. https://github.com/sallar/stringz/blob/master/CHANGELOG.md 
- unit tests still passing
----
> chore: Bump stringz package version

- CHANGELOG.md
- package.json
I messed up the versions in this package trying to get a new release out.
Good thing is that no new release was pushed out so we can revert the version with no risk.
After going through some GH actions' logs it seems that I need to use either `fix` or `feature` so the commitlint trigger the release process.
--
----
> fix: This reverts PR #263

- helpers/3p/utils/lib/markdown.js
- package.json
- spec/helpers/3p/markdown.js
- spec/helpers/3p/utils/lib/markdown.js
JIRA: [STRF-10493](https://bigcommercecloud.atlassian.net/browse/STRF-10493)
`markdown` helper produces multi-line logs that are not even needed in debug mode so we remove those logs and enable the `Remarkable` lib configuration.
Unit tests for `Remarkable` configuration were enabled.
All unit tests are green.
----
[STRF-10493]: https://bigcommercecloud.atlassian.net/browse/STRF-10493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: STRF-10493 Address markdown helper messy logs

- helpers/cdn.js
- spec/helpers/cdn.js
A customer reported that `cdn` helper was no able to construct a proper early hint (specifically the usage of `crossorigin` attribute).
- unit tests
----
> fix: fixes cdn helper early hint construction

- helpers/money.js
- spec/helpers/money.js
Currently, the `money` helper will not properly position the currency symbol if the setting received has a capital letter. I found that on some stores, the currency location can sometimes default with the first letter capitalized (e.g. `Left` instead of `left`)
The currency location should not be case sensitive.
- Unit tests
----
> fix: STRF-10878 Fix money symbol position when setting is capitalized

- .github/workflows/build.yml
those CI actions are running on old node versions
----
> fix: bump deprecated github actions

- .github/workflows/release.yml
- package.json
- Bump Release GA versions
- Bump semantic release
----
> fix: bump release step github actions and semantic release

- helpers/lib/cdnify.js
- spec/helpers/cdn.js
Use CDN Original images for webdav - cache control. 
If a developer/merchant decide to use the handlebar to import images from WebDav into the theme `({{cdn "webdav:/img/image.jpg"}})`, there is no cache-control header when the image is presented to the storefront.
Similar to our Image Manager, we should be using the cdn original images (Similar to Jinsoo's PR here [MERC-7127](https://github.com/bigcommerce/bigcommerce/pull/47254)
Example images:
[Original /content/](https://cdn11.bigcommerce.com/s-hc1qesrzsh/content/webdev-pat.jpg)
[Updated /images/stencil/original/content/](https://cdn11.bigcommerce.com/s-hc1qesrzsh/images/stencil/original/content/webdev-pat.jpg)
Tested locally
[MERC-7127]: https://bigcommercecloud.atlassian.net/browse/MERC-7127?atlOrigin= …
> feat(merc): MERC-9364 Use CDN Original images for webdav - cache control

- helpers/moment.js
- package.json
- spec/helpers/moment.js
date.js have several bugs, is not supported and outdated.
chrono provides same capabilities
npm test
----
> fix: STRF-9936 Replaced outdated date.js with chrono

- package.json
bump handlebars to 4.7.8
cdvm
----
> fix: STRF-11164 bump handlebars v4 to 4.7.8

- spec/helpers/block.js
Show case working fallback case for partials
npm test
----
> fix: make fallback case explicit in unit tests

- helpers/nonce.js
- spec/helpers/nonce.js
Wrap nonce output into SafeString, so it doesn't get double quote on the browser
Before
After
----
> fix: strf-11673 Wrap nonce into SafeString

- helpers/nonce.js
- spec/helpers/nonce.js
https://bigcommercecloud.atlassian.net/browse/STRF-11941
Just return nonce in double quotes 
Dev VM
Before:
After:
----
> chore(storefront): STRF-11941 Helper should just return nonce in quotes

- helpers/nonce.js
- spec/helpers/nonce.js
Remove the quotes from nonce helper. 
Collaboration with Merchandising on nonce.
Run storefront-renderer-2 locally with local paper and paper handlebars via npm link
1. cd into local paper and paper handlebars directories `npm link`
2. Then in storefront-renderer-2 
`npm link @bigcommerce/stencil-paper `
`npm link @bigcommerce/stencil-paper-handlebars`
3. dev.yml
```
storefront-renderer-2:
rpc:
port: 9998
```
----
cc @bigcommerce/storefront-team cc @jkanive @bc-erich
> fix(storefront): STRF-11941 Remove quotes from nonce

- helpers/block.js
- helpers/partial.js
- spec/helpers/block.js
Prevent `partial` and `block` helpers from allowing names that are the same as native javascript object prototype methods.
Roll back this PR
Unit tests, ensured that error is not thrown and object prototype is not accessed.
----
cc @bigcommerce/team-storefront 
[STRF-12281]: https://bigcommercecloud.atlassian.net/browse/STRF-12281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(storefront): STRF-12281 Prevent block and partial helpers from being named prototype methods

- index.js
- lib/errors.js
- spec/index.js
Add Precompile Error for renderString.
EmailRenderer had validation logic that was relying on another error type that is not thrown anymore, so had to add a new type 
npm test / email-renderer
----
> feat: add precompile error for renderString

- helpers/moment.js
- spec/helpers/moment.js
- Make moment.js to warn instead of error
npm test
----
> fix: STRF-12234 Make moment.js to warn instead of error

- index.js
- spec/index.js
Set "Handlebars: Access has been denied to resolve the property" message to info level
`npm test`
----
> fix: STRF-12532 Set Access has been denied to resolve the property message to info level

- helpers/jsonParseSafe.js
- spec/helpers/jsonParseSafe.js
Add patch to allow for #JSONparseSafe to be used as a inline helper.
Examples:
`{{log (JSONparseSafe '{"test":"variable"}')}}`
`{{log (lookup (JSONparseSafe '{"test":{"validate":"variable"}}') "test")}}`
To prevent this situation which makes code so much harder to maintain and reason with:
```Handlebars
{{! Pretend at this layer there is a pagination object here }}
{{! Before}}
{{#JSONparseSafe '{"test": "hello world!"}'}}
{{#with this}}
{{log test}}
{{log ../../pagination}}
{{/with}}
{{/JSONparseSafe}}
{{! After}}
{{#with (JSONparseSafe '{"test": "hello world!"}')}}
{{log test}}
{{log ../pagination}}
{{/with}}
```
This change removes a extra layer of context shifting `( ../ )` to access information about the context window.
Local tests, modified local theme testing file.
----
cc …
> feat: Update jsonParseSafe.js - Inline use patch

- helpers/assignVar.js
- helpers/decrementVar.js
- helpers/incrementVar.js
- helpers/inject.js
- spec/helpers/decrementVar.js
- spec/helpers/incrementVar.js
- Object.create(null) insted of {}
npm test 
----
> fix: STRF-13111 Object.create(null) insted of empty object

- .github/workflows/build.yml
- spec/helpers/dynamicComponent.js
- Enable windows and ubuntu for the pipeline
- Fix dynamicComponent test for windows
npm test
----
> ci: enable windows as OS for running tests

- helpers/assignVar.js
- spec/helpers/assignVar-getVar.js
Helper `assignVar` currently does not have a way to do any of the following features:
1. Un-Map a assigned value: once a key has been set, it is locked for the whole render pipeline. This results in features like widgets taking up half of the available variables only to use them once and never again, limiting theme developers from being able to add new features due to limited variable space.
2. Accept an empty string into a variable as its value. Given a string is valid input, all states of a string should be considered as valid, limited by length. For instance, if a variable is set to `""` because it is intended to be a placeholder when a value is not provided by the store admins or a customer input, say for a phone number click to call, this will currently cause the store to err.500 …
> feat(assignVar): Patch for assignVar to add "drop key" feature and fixes reflecting documentation

- index.js
- spec/index.js
Disable log helper for rendering services
More [here](https://github.com/bigcommerce/storefront-renderer-2/pull/155)
npm test
----
> fix: STRF-13182 disable log helper for rendering services

- package.json
set chrono-node version to 2.8.0 as 2.8.1 is not a working version
npm test
----
> fix: set chrono-node to 2.8.0
