- .eslintignore
- .travis.yml
- README.md
- npm-shrinkwrap.json
- package.json
* Lock dependency for handlebars-v4
* Add shrinkwrap file
* Minor cleanup
`rm -rf node_modules && npm install`
----
> Add shrinkwrap

- .travis.yml
- helpers.js
- index.js
- spec/helpers/all.js
- spec/spec-helpers.js
Add Node 4 to Travis and make necessary changes
`nvm use 4`
`npm install && npm test`
----
> Minor changes to support Node 4.x

- CHANGELOG.md
- package.json
Bump package.json version and adds changelog entry for the recent region helper change in #23 
----
cc @bigcommerce/storefront-team @bigcommerce/merc-team
> Releasing v4.0.2

- CHANGELOG.md
- package.json
> Release v4.0.3

- CHANGELOG.md
- package.json
> Release v4.0.5

- CHANGELOG.md
- package.json
update changelog and package.json to reflect version update.
It was not.
----
> update changelog and package.json for version 4.0.6

- CHANGELOG.md
- helpers/lib/cdnify.js
- spec/helpers/cdn.js
https://jira.bigcommerce.com/browse/STRF-6711 The regex usage in cdnify is fairly expensive. Figure out an alternative.  This pull request is for that alternative.
----
unit tests still pass.  Used regular expression analyzer to figure out what the regex statements were testing for.  Solution somewhat loosely translated can be more strict.
> STRF-6711 Remove cdn regex

- CHANGELOG.md
- package.json
Release 4.0.7
- Remove regex in cdnify.js to improve performance
- Remove regex in fonts.js for better performance
- Refactor functions away from arguments pattern for better performance
- Fix for helper to allow for one iteration
- Reduce usage of Lodash to improve performance
----
> Release 4.0.7

- CHANGELOG.md
- package.json
> STRF-6935: Release 4.0.9

- .travis.yml
- package.json
> Start testing Node 12 in travis

- README.md
@bigcommerce/storefront-team
Add npm version shield on the readme file
See https://img.shields.io/npm/v/@bigcommerce/stencil-paper-handlebars.svg
> Add npm version shield on the readme file

- helpers/json.js
- helpers/lib/common.js
- helpers/setURLQueryParam.js
- helpers/stripQuerystring.js
Moving this to a common function in order to DRY.
Unit tests.
> Move SafeString unwrapping to common.js

- CHANGELOG.md
- package.json
Bump and update changelog.
----
> Bump paper-handlebars to 4.2.1

- helpers/thirdParty.js
Supress deprecation warnings in the moment library. These unfortunately spit a stack trace out to console.error, so it's not very a very friendly interface.
`npm test`
----
> STRF-7500: Supress moment deprecation warnings

- index.js
Add ability to pass a console-like object to PaperHandlebars, which will then be used for handlebars logging, including for the `log` helper.
`npm test`
----
> STRF-7500: Ability to set handlebars logger

- CHANGELOG.md
- index.js
- package.json
- spec/index.js
* Add test for logger
* Update Sinon
* Release 4.23.
`npm test`
----
> Release 4.2.3

- spec/helpers/encodeHtmlEntities.js
Improving test based on feedback from @lord2800 , and fixing a bad copy/paste.
Tests.
----
> Fix tests for encodeHtmlEntities helper

- CHANGELOG.md
- package.json
> Bump 4.3.2

- .travis.yml
> Add node 14 to Travis

- package.json
Update handlebars 3.x branch to latest
`npm test`
----
> PEN-1910: Update handlebars 3.x

- .gitignore
- package.json
Update 4.x branch to latest
`npm test`
----
> PEN-1911: Update to latest handlebars 4.x

- CHANGELOG.md
- package.json
Release 4.4.1. Contains version bumps for handlebars 3.x and 4.x
----
> Release 4.4.1

- .gitignore
- CHANGELOG.md
- helpers/all.js
- helpers/any.js
- helpers/contains.js
- helpers/deprecated/pick.js
- helpers/lib/fonts.js
- helpers/money.js
- helpers/or.js
- helpers/pluck.js
- helpers/resourceHints.js
- helpers/stylesheet.js
- package.json
Refactor our helpers and remove unneeded dependency
Unit test coverage. Will be manually testing as well
> Refactor helpers and remove unneeded dependency

- helpers/contains.js
- spec/helpers/any.js
- spec/helpers/contains.js
Adds test coverage for contains helper. It looks like we were previously missing coverage for this helper. Added some additional edge case testing.
Unit tests added.
----
> STRF-8666: Adds test coverage for contains helper

- helpers/pluck.js
- package.json
- spec/helpers/pluck.js
Fix pluck helper and support nested fetch
unit test in place
----
> Fix pluck helper and support nested fetch

- helpers/pluck.js
- package.json
- spec/helpers/pluck.js
Reverts bigcommerce/paper-handlebars#108
@bigcommerce/storefront-team
> Revert "Fix pluck helper and support nested fetch"

- CHANGELOG.md
- helpers/all.js
- helpers/any.js
- helpers/contains.js
- helpers/deprecated/pick.js
- helpers/lib/fonts.js
- helpers/money.js
- helpers/or.js
- helpers/pluck.js
- helpers/resourceHints.js
- helpers/stylesheet.js
- package.json
This reverts commit 6633db45abeb4c75fe2750c6fd40703c58edfc57.
This is a manual revert of https://github.com/bigcommerce/paper-handlebars/pull/102/
The only change which I have kept is the `gitignore` change
`
`npm run test`
> Revert "Refactor helpers and remove unneeded dependency"

- CHANGELOG.md
- package.json
> chore: release 4.4.2

- README.md
see https://github.com/bigcommerce/paper-handlebars/workflows/Build/badge.svg
> Update build status badge to use github actions

- helpers/inject.js
- spec/helpers/inject.js
Reverts bigcommerce/paper-handlebars#116
Since release freeze is over we should be able to introduce this change.
> Revert "Revert "STRF-8585 Escape injected values""

- CHANGELOG.md
- package.json
> Release 4.4.4

- helpers/inject.js
- spec/helpers/inject.js
Reverts bigcommerce/paper-handlebars#126
> Revert "Revert "Revert "STRF-8585 Escape injected values"""

- CHANGELOG.md
- package.json
> Release 4.4.5

- CHANGELOG.md
- package.json
> Release 4.4.6

- helpers/lib/common.js
- helpers/setURLQueryParam.js
Replaced URL constructor with url.parse functionality
There are around 8 test suites that covers this method, so I didn't add new tests for this. 
`npm test`
----
> STRF-9083 Fix handlebars helpers using node package url

- CHANGELOG.md
- package.json
> Release 4.4.7

- README.md
> Fix a readme link

- .github/workflows/release.yml
Publish package through github release
----
> STRF-9318 Release stencil paper handlebars through github release

- .github/workflows/build.yml
- .github/workflows/release.yml
> Stop testing on node 10, start testing on node 14, release on 14

- helpers/lib/resourceHints.js
- helpers/stylesheet.js
- index.js
- spec/helpers/lib/resourceHints.js
- spec/helpers/stylesheet.js
JIRA: [STRF-9950](https://bigcommercecloud.atlassian.net/browse/STRF-9950)
`stylesheet` helper is now able to produce resource hints.
uni tests
----
> [STRF-9950] paper-handlebars - stylesheet helper early-hints flag

- helpers.js
- helpers/earlyHint.js
- spec/helpers.js
- spec/helpers/earlyHint.js
a new passthrough helper `earlyHint`.
unit tests
----
> [STRF-9947] new helper earlyHint

- CHANGELOG.md
- package.json
> chore: release 5.1.1

- CHANGELOG.md
- package.json
> chore: release 5.1.2

- CHANGELOG.md
- package.json
> chore: release 5.1.5

- CHANGELOG.md
- package.json
> chore: release 5.1.7

- .releaserc
- commitlint.config.js
Ignore case in sentence case rule for commit messages
locally
----
> fix: STRF-10157 Ignore case in sentence case rule

- helpers/cdn.js
- helpers/earlyHint.js
- helpers/lib/fonts.js
- helpers/resourceHints.js
- helpers/stylesheet.js
Jira: https://bigcommercecloud.atlassian.net/browse/STRF-10188
adds logs for errors at early-hint generation calls.
given that only logs were added, unit tests are our safety net here.
----
> fix: STRF-10188 adds logs at early hint generation calls

- helpers/3p/utils/base.js
- helpers/3p/utils/lib/deepMatches.js
- helpers/3p/utils/lib/makeIterator.js
- helpers/all.js
- helpers/any.js
- helpers/contains.js
- helpers/deprecated/pick.js
- helpers/lib/fonts.js
- helpers/or.js
- helpers/pluck.js
- package.json
- spec/helpers/3p/utils/lib/markdown.js
- spec/helpers/thirdParty.js
Removed lodash from runtime dependencies (it's still used in dev dependencies)
npm test
----
> feat: strf- 9673 Remove lodash from paper-handlebars deps

- helpers/3p/array.js
- helpers/3p/string.js
- helpers/3p/utils/index.js
- helpers/contains.js
- spec/helpers/3p/array.js
- spec/helpers/thirdParty.js
More validation on helpers:
- eachIndex
- last 
- uppercase
- isUndefined
- contains
npm test
----
> fix: STRF-9673 Lodash removal fixes, part 2

- helpers/3p/array.js
- helpers/pluck.js
- helpers/truncate.js
- spec/helpers/3p/array.js
- spec/helpers/truncate.js
Helpers: pluck, after, truncate
npm test
----
> fix: STRF-9673 Lodash removal, part 3

- helpers/3p/utils/lib/arrayFilter.js
- helpers/3p/utils/lib/arraySort.js
- helpers/3p/utils/lib/createFrame.js
- helpers/3p/utils/lib/isOdd.js
- helpers/assignVar.js
- helpers/compare.js
- helpers/decrementVar.js
- helpers/encodeHtmlEntities.js
- helpers/getImageSrcset1x2x.js
- helpers/getVar.js
- helpers/if.js
- helpers/incrementVar.js
- helpers/lib/fonts.js
- helpers/lib/getObjectStorageImage.js
- helpers/lib/resourceHints.js
- helpers/money.js
- helpers/setURLQueryParam.js
- helpers/strReplace.js
- index.js
- lib/errors.js
- spec/index.js
All validation errors should be the instance of ValidationError
npm test
----
> feat: STRF-10408 Categorize validaiton error as ValidationError

- CHANGELOG.md
- package.json
Update package.json and changelog to get versions back in sync.
----
> chore(release): update release 5.7.8

- .github/workflows/build.yml
- .github/workflows/release.yml
- package.json
Update CI to use Node 18
npm test, CI
----
> feat: Build CI using Node 18

- CHANGELOG.md
- package.json
Update changelog and package.json
----
> chore(release): update release 5.8.0

- .github/workflows/release.yml
> fix: empty PR to test CI changes in fork

- .github/workflows/release.yml
Removed unused env vars. 
----
> fix: STRF-11050 Remove unused env vars

- .github/workflows/release.yml
test `persist-credentials: false`
----
> fix: set persist credentials false for actions/checkout

- index.js
empty PR to trigger CI
on forked repo
----
> fix: STRF-11050 Fix pipeline by forking semantic-release-github-pullrequest

- index.js
Fixed creating PR for automating github Pull Request creation. 
in forked repo
----
> fix: bump PR to deploy new version

- helpers/lib/cdnify.js
- spec/helpers/cdn.js
Reverts bigcommerce/paper-handlebars#273
> fix(merc): MERC-9364 Reverts CDN Webdav

- helpers.js
- helpers/nonce.js
- index.js
- spec/helpers.js
- spec/helpers/nonce.js
- spec/spec-helpers.js
- Pass down to handlebars request params object from stencil context.
- Added nonce helper that reads from request params object
npm test
----
> feat: STRF-11673 Add nonce helper

- .github/workflows/build.yml
Address security issues
https://bigcommercecloud.atlassian.net/browse/STRF-11934
----
> fix: STRF-11934 Move PR Title to env

- helpers/3p/array.js
- helpers/3p/collection.js
- helpers/3p/comparison.js
- helpers/3p/html.js
- helpers/3p/misc.js
- helpers/3p/object.js
- helpers/3p/string.js
- helpers/3p/utils/lib/arraySort.js
- helpers/assignVar.js
- helpers/decrementVar.js
- helpers/incrementVar.js
- helpers/inject.js
- index.js
- spec/helpers/decrementVar.js
- spec/helpers/incrementVar.js
- Use last argument from arguments object instead of function arguments
- Use Object.create(null) instead of {}
- Add knownHelpers attribute
npm test
----
> fix: STRF-13111 Helpers last arguments improvements and fixes

- helpers/3p/array.js
- helpers/3p/collection.js
- helpers/3p/comparison.js
- helpers/3p/html.js
- helpers/3p/misc.js
- helpers/3p/object.js
- helpers/3p/string.js
- helpers/3p/utils/lib/arraySort.js
- helpers/assignVar.js
- helpers/decrementVar.js
- helpers/incrementVar.js
- helpers/inject.js
- index.js
- spec/helpers/decrementVar.js
- spec/helpers/incrementVar.js
Reverts bigcommerce/paper-handlebars#347
> Revert "fix: STRF-13111 Helpers last arguments improvements and fixes"

- helpers/3p/array.js
- index.js
- spec/helpers/money.js
- Added stack trace to RenderError message, that is used for rendering scripts
- arguments improvements for array helpers
npm test
----
> fix: STRF-13111 Add stack trace to RenderError; arguments improvements for array helpers

- helpers/3p/collection.js
- helpers/3p/string.js
Arguments improvements for collection and string helpers
npm test 
----
> fix: STRF-13111 Helpers last arguments improvements and fixes: collection and string helpers
